name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        run: |
          wget -qO- https://toolbelt.heroku.com/install.sh | sh
          heroku --version

      - name: Login to Heroku
        run: heroku login -i

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a ulbi-project-backend
          git push heroku main
